version: '3.8'  # Specify the version

services:

  # Service MySQL
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: api_spring
      MYSQL_USER: root
      MYSQL_PASSWORD: Buster
    volumes:
      - ./api_parc.sql:/docker-entrypoint-initdb.d/api_parc.sql
    ports:
      - "3306:3306"
    networks:
      - api_network

  # Service Redis
  redis:
    image: redis:7.0
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - api_network

  # Service Spring Boot (from Dockerfile)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_api_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/api_parc
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Buster
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - db
      - redis
    networks:
      - api_network

networks:
  api_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16  # Custom subnet
