services:
  
  # Service MySQL
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: blog_spring
      MYSQL_USER: root
      MYSQL_PASSWORD: Buster
    volumes:
      - ./blog_spring.sql:/docker-entrypoint-initdb.d/api_parc.sql
    ports:
      - "3306:3306"
    networks:
      - blog_network

  # Service Redis
  redis:
    image: redis:7.0
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - blog_network

  # Service Spring Boot (à partir de Dockerfile)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_blog_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/api_parc
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Buster
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - db
      - redis
    networks:
      - blog_network

networks:
  blog_network:
    driver: bridge

